ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyUSB1
    frame_id: lidar_link
    ignore_array: ""
    baudrate: 115200
    lidar_type: 1
    device_type: 0
    sample_rate: 3
    frequency: 7.0
    fixed_resolution: true
    reversion: false
    inverted: false
    auto_reconnect: true
    isSingleChannel: true
    intensity: false
    support_motor_dtr: true
    angle_min: -180.0
    angle_max: 180.0
    range_min: 0.12
    range_max: 10.0
    abnormal_check_count: 4
    invalid_range_is_inf: false
